name: Bazel build

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # macos-latest
    steps:
      -
        name: Date-Based Cache key
        # get a key showing the current week (ISO: yyyyWww)
        id: week
        run: echo "::set-output name=iso::$(date +'bazel-%YW%U')"
      -
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Cache bazel downloads via bazelisk
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ steps.week.outputs.iso }}
          # Share repository cache between workflows.
          repository-cache: true
      -
        uses: actions/checkout@v4
      -
        run: bazel build //...
      -
        run: bazel test //... --test_summary=detailed --test_output=errors
      -
        run: bazel test //:langchain_test
      -
        run: bazel run //:requirements.update
      -
        run: bazel test //... --test_summary=detailed --test_output=errors
